"""message

Revision ID: 2a58ebf9091f
Revises: a891b465b6c2
Create Date: 2026-02-26 20:26:48.375057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a58ebf9091f'
down_revision: Union[str, None] = 'a891b465b6c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _column_exists(connection: sa.engine.Connection, table: str, column: str) -> bool:
    result = connection.execute(
        sa.text(
            "SELECT 1 FROM information_schema.columns "
            "WHERE table_name = :table AND column_name = :column"
        ),
        {"table": table, "column": column},
    )
    return result.scalar() is not None


def _index_exists(connection: sa.engine.Connection, index_name: str) -> bool:
    result = connection.execute(
        sa.text(
            "SELECT 1 FROM pg_indexes WHERE indexname = :index_name"
        ),
        {"index_name": index_name},
    )
    return result.scalar() is not None


def _fk_exists(connection: sa.engine.Connection, table: str) -> bool:
    result = connection.execute(
        sa.text(
            "SELECT 1 FROM information_schema.table_constraints tc "
            "JOIN information_schema.key_column_usage kcu "
            "ON tc.constraint_name = kcu.constraint_name "
            "WHERE tc.table_name = :table AND tc.constraint_type = 'FOREIGN KEY' "
            "AND kcu.column_name = 'type_id'"
        ),
        {"table": table},
    )
    return result.scalar() is not None


def upgrade() -> None:
    connection = op.get_bind()

    if not _column_exists(connection, "annotation_list", "type_id"):
        op.add_column("annotation_list", sa.Column("type_id", sa.String(), nullable=True))

    if _index_exists(connection, "ix_annotation_list_type"):
        op.drop_index(op.f("ix_annotation_list_type"), table_name="annotation_list")

    if not _index_exists(connection, "ix_annotation_list_type_id"):
        op.create_index(
            op.f("ix_annotation_list_type_id"), "annotation_list", ["type_id"], unique=False
        )

    if not _fk_exists(connection, "annotation_list"):
        op.create_foreign_key(
            None, "annotation_list", "annotation_type", ["type_id"], ["id"], ondelete="CASCADE"
        )

    if _column_exists(connection, "annotation_list", "type"):
        op.drop_column("annotation_list", "type")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('annotation_list', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'annotation_list', type_='foreignkey')
    op.drop_index(op.f('ix_annotation_list_type_id'), table_name='annotation_list')
    op.create_index(op.f('ix_annotation_list_type'), 'annotation_list', ['type'], unique=False)
    op.drop_column('annotation_list', 'type_id')
    # ### end Alembic commands ###
