"""message

Revision ID: 2a58ebf9091f
Revises: a891b465b6c2
Create Date: 2026-02-26 20:26:48.375057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a58ebf9091f'
down_revision: Union[str, None] = 'a891b465b6c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('annotation_list', sa.Column('type_id', sa.String(), nullable=True))
    op.drop_index(op.f('ix_annotation_list_type'), table_name='annotation_list')
    op.create_index(op.f('ix_annotation_list_type_id'), 'annotation_list', ['type_id'], unique=False)
    op.create_foreign_key(None, 'annotation_list', 'annotation_type', ['type_id'], ['id'], ondelete='CASCADE')
    op.drop_column('annotation_list', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('annotation_list', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'annotation_list', type_='foreignkey')
    op.drop_index(op.f('ix_annotation_list_type_id'), table_name='annotation_list')
    op.create_index(op.f('ix_annotation_list_type'), 'annotation_list', ['type'], unique=False)
    op.drop_column('annotation_list', 'type_id')
    # ### end Alembic commands ###
