"""add_cascade_delete_to_user_rejected_texts

Revision ID: 55130b300fc5
Revises: 2da239d357e7
Create Date: 2025-07-07 18:12:59.332438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55130b300fc5'
down_revision: Union[str, None] = '2da239d357e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('user_rejected_texts_text_id_fkey'), 'user_rejected_texts', type_='foreignkey')
    op.drop_constraint(op.f('user_rejected_texts_user_id_fkey'), 'user_rejected_texts', type_='foreignkey')
    op.create_foreign_key(None, 'user_rejected_texts', 'texts', ['text_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_rejected_texts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_rejected_texts', type_='foreignkey')
    op.drop_constraint(None, 'user_rejected_texts', type_='foreignkey')
    op.create_foreign_key(op.f('user_rejected_texts_user_id_fkey'), 'user_rejected_texts', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('user_rejected_texts_text_id_fkey'), 'user_rejected_texts', 'texts', ['text_id'], ['id'])
    # ### end Alembic commands ###
