"""add name field to annotations

Revision ID: 79d0d9fbf4b0
Revises: 
Create Date: 2025-07-03 17:44:01.459360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79d0d9fbf4b0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('annotations', sa.Column('name', sa.String(), nullable=True))
    op.alter_column('texts', 'status',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('texts', 'status',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'initialized'::character varying"),
               existing_nullable=False)
    op.drop_column('annotations', 'name')
    # ### end Alembic commands ###
