"""make_annotator_id_nullable_for_system_annotations

Revision ID: 7c634d86ca15
Revises: 55130b300fc5
Create Date: 2025-07-07 18:29:49.922203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c634d86ca15'
down_revision: Union[str, None] = '55130b300fc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('annotations', 'annotator_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('annotations', 'annotator_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
