"""add uploader_id and annotation_typ_id to annotation_type and text table respectively

Revision ID: a891b465b6c2
Revises: f402fb478068
Create Date: 2025-10-16 16:01:18.901905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a891b465b6c2'
down_revision: Union[str, None] = 'f402fb478068'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('annotation_type', sa.Column('uploader_id', sa.String(), nullable=True))
    op.drop_constraint(op.f('annotation_type_name_key'), 'annotation_type', type_='unique')
    op.create_index(op.f('ix_annotation_type_uploader_id'), 'annotation_type', ['uploader_id'], unique=False)
    op.create_foreign_key(None, 'annotation_type', 'users', ['uploader_id'], ['auth0_user_id'])
    op.drop_column('annotation_type', 'description')
    op.drop_column('annotation_type', 'meta')
    op.add_column('texts', sa.Column('annotation_type_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'texts', 'annotation_type', ['annotation_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'texts', type_='foreignkey')
    op.drop_column('texts', 'annotation_type_id')
    op.add_column('annotation_type', sa.Column('meta', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('annotation_type', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'annotation_type', type_='foreignkey')
    op.drop_index(op.f('ix_annotation_type_uploader_id'), table_name='annotation_type')
    op.create_unique_constraint(op.f('annotation_type_name_key'), 'annotation_type', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_column('annotation_type', 'uploader_id')
    # ### end Alembic commands ###
