"""add_cascade_delete_to_annotations

Revision ID: b9d95473d6a0
Revises: ca9d64d39e72
Create Date: 2025-07-07 11:59:17.834366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9d95473d6a0'
down_revision: Union[str, None] = 'ca9d64d39e72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('annotations_text_id_fkey', 'annotations', type_='foreignkey')
    op.create_foreign_key(None, 'annotations', 'texts', ['text_id'], ['id'], ondelete='CASCADE')
    op.drop_index('ix_texts_title', table_name='texts')
    op.create_index(op.f('ix_texts_title'), 'texts', ['title'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_texts_title'), table_name='texts')
    op.create_index('ix_texts_title', 'texts', ['title'], unique=False)
    op.drop_constraint(None, 'annotations', type_='foreignkey')
    op.create_foreign_key('annotations_text_id_fkey', 'annotations', 'texts', ['text_id'], ['id'])
    # ### end Alembic commands ###
