"""update the created_by fkey reference column

Revision ID: cb9d78c60ba0
Revises: 487e729d5cef
Create Date: 2025-10-07 11:27:38.025242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb9d78c60ba0'
down_revision: Union[str, None] = '487e729d5cef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('annotation_list_created_by_fkey'), 'annotation_list', type_='foreignkey')
    op.alter_column('annotation_list', 'created_by',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_foreign_key(None, 'annotation_list', 'users', ['created_by'], ['auth0_user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'annotation_list', type_='foreignkey')
    op.alter_column('annotation_list', 'created_by',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.create_foreign_key(op.f('annotation_list_created_by_fkey'), 'annotation_list', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###
